### ISSUE TITLE
no module named phenoscore

### ISSUE THREAD

**Issue by GauravPrajapati96** [ldingemans/PhenoScore#10]
hey this is an amazing package and i want to utilize it in my study, but when I installed it and ran the tutorial .ipynb file I faced an error 

ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_37800\2943989098.py in <module>
----> 1 from phenoscore.phenoscorer import PhenoScorer
      2 import os

ModuleNotFoundError: No module named 'phenoscore'

this error is in first line itself .

kindly help me with this.

thanks in advance. i am looking forward for your response

**Comment by ldingemans** [comment]
thank you for your interest in phenoscore! 

did you try to actually install the module, with ``pip install .`` in the root directory of phenoscore? because it looks like it wasn't properly installed

**Comment by GauravPrajapati96** [comment]
Thank you for your response. I already went through pip install . as mention in the  readme.md  but the same error is occuring again as mention above .

**Comment by ldingemans** [comment]
if you run a python console instance, can you import phenoscore (using ``import phenoscore``)? Did it install correctly and did you install it a) in the correct environment and b) did you activate the environment to make sure you have access to the installed module?

**Comment by GauravPrajapati96** [comment]
Thank you so much for your valuable and immediate response. The PhenoScore has run successfully.
