### ISSUE TITLE
Issue about tensorflow==2.5.0 in Mac M1

### ISSUE THREAD

**Issue by Ivanfxia** [ldingemans/PhenoScore#11]
Hi, I'm trying use the PhenoScore on M1 chip Macbook, I cannot install tensorflow==2.5.0. Then I install tensorflow 2.16.1, but it not work. Could you help me solve it? Thank you a lot!

from phenoscore.phenoscorer import PhenoScorer
import os

ImportError: cannot import name 'LocallyConnected2D' from 'tensorflow.keras.layers' (/Users/ivanxia/miniconda3/envs/PhenoScore/lib/python3.9/site-packages/keras/_tf_keras/keras/layers/__init__.py)

**Comment by ldingemans** [comment]
Hi @Ivanfxia, thank you for your interest in PhenoScore! 

Could you maybe try with the ``develop`` branch? We're trying to remove the ``tensorflow`` dependencies specifically for the reasons you mentioned. I do not have Mac myself so cannot test it unfortunately, but have good hopes installation will go smoother with that branch. 

If not, be sure to let us know into what issues you run!

**Comment by ldingemans** [comment]
Closed because of lack of response
