### ISSUE TITLE
Saving Trained Model in "phenoscorer" for Efficient Inference

### ISSUE THREAD

**Issue by DWuuuuuu** [ldingemans/PhenoScore#13]
I am wondering if there is a way to save the trained model in the [tutorial.ipynb](notebooks/tutorial.ipynb) for "phenoscorer," so that running inference with the "phenoscorer.predict_new_sample" function can be more convenient and efficient. Thanks!

**Comment by ldingemans** [comment]
hey @DWuuuuuu thanks for your interest in PhenoScore. We have not added specific support to export/import models, but I think pickling them should work? See https://stackoverflow.com/questions/4530611/saving-and-loading-objects-and-using-pickle for more information.

Please do let me know if you run into issues!
