### ISSUE TITLE
from collections import Counter keeps giving a TypeError

### ISSUE THREAD

**Issue by RodneyKoolman** [ldingemans/PhenoScore#8]
![image](https://github.com/ldingemans/PhenoScore/assets/24556645/b3c498c3-438f-4403-a2bf-c5d56d6e491b)

I'm trying to run the model but keep running into this issue. I'm running miniconda3 for all my projects but when running the notebook it keeps returning this error. Wondering if you had any such issue?

**Comment by RodneyKoolman** [comment]
Digging deeper into the lib collections it gives the warning. It's running the interpreter 3.9.17 like you suggested.
Don't know what I'm missing here...

Import "_collections" could not be resolved

**Comment by RodneyKoolman** [comment]
Not running it in notebooks gets me a little further. Getting different errors. Digging even deeper, seeing that phenopy/config.py tries to access a os.path named HOME. That doesn't exist on Windows. Are you running linux?

**Comment by ldingemans** [comment]
> Not running it in notebooks gets me a little further. Getting different errors. Digging even deeper, seeing that phenopy/config.py tries to access a os.path named HOME. That doesn't exist on Windows. Are you running linux?

We have been mainly running Linux indeed, but I think I know what the issue is on Windows. Could you try this fix?

[https://github.com/GeneDx/phenopy/issues/48](https://github.com/GeneDx/phenopy/issues/48)

**Comment by RodneyKoolman** [comment]
Thanks! That works. Onto the next error. Did you see this one before?

![image](https://github.com/ldingemans/PhenoScore/assets/24556645/8c4987d1-33df-45d6-b3b6-155fe4078418)

**Comment by ldingemans** [comment]
No, Ive not encountered that before. What is your mxnet version?

**Comment by RodneyKoolman** [comment]
![image](https://github.com/ldingemans/PhenoScore/assets/24556645/57d6adde-eff4-4b2e-b994-1ed92613b2a4)

1.2.0. No version is specified in the requirements file so i guess it's the latest.

**Comment by ldingemans** [comment]
Thats strange, its a pretty old version (although I could have specified that).

Could you try installing a newer version? 1.7.0 for instance? i.e. ``pip install mxnet==1.7.0.post2`` 

If thats the issue, I will update the ``requirements.txt``

**Comment by ldingemans** [comment]
I've just verified on a windows machine that I can install ``1.7.0``, so not sure what is going wrong then?

**Comment by RodneyKoolman** [comment]
Hmm that's weird. What's you numpy version there?

**Comment by ldingemans** [comment]
related to numpy on windows maybe? here are some pointers https://github.com/numpy/numpy/issues/13573?

**Comment by RodneyKoolman** [comment]
Yes i got it to work! Thanks for you help. Now the above pip commands work.
The solution was hidden in the install mxnet==1.7.0.post2 error. It needed the VS C++ Build Tools installed. Did that and it worked like a charm. Looks like it's running the tutorial data now.

![image](https://github.com/ldingemans/PhenoScore/assets/24556645/5cebcb72-cdce-4786-919a-6aa67178b592)

I haven't got the GPU inference to work. It gives me missing library's error but will look at that for another day. CPU inference is working. Can't get this to work in the Jupyter notebooks, just made a py script for now.

Thanks for your support and work!

**Comment by RodneyKoolman** [comment]
FYI got the CUDA part working.
After doing "conda install cudnn" you need to download zlibwapi.dll and add it to the system PATH env variable. Now GPU inference is working.

**Comment by ldingemans** [comment]
great to hear you've solved it! Thanks for opening the issue - and closing it now that it is clear. I will look into CI for Windows a bit more if there are more users that have issues installing it on Windows.

Good luck with using PhenoScore in your research - be sure to let me know if there are other problems, are if things are unclear (in the documentation for instance), or missing etc.
